# 第二章 Numpy数值计算基础
## 学习目标
- Numpy创建多维数组和生成随机数的方法
- 数组的索引与变换
- Numpy中数组矩阵的运算及通用函数的基本使用方法
- Numpy读写文件的方法和常用的统计分析函数

In [3]:
# 显示所有变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np

In [4]:
# 从文本文件读取人口数据
peoples = np.loadtxt("data/人口.csv",skiprows=2,delimiter=',',usecols=(range(1,13)),encoding="utf-8")
province = np.loadtxt("data/人口.csv",skiprows=2,delimiter=',',usecols=0,encoding="utf-8",dtype=str)

## 2.1 掌握 NumPy 数组对象 ndarray
Python 提供了一个array 模块。array 和list 不同，它直接保存数值，和C 语言的一维
数组比较类似。但是由于Python 的array 模块不支持多维，也没有各种运算函数，因此也
不适合做数值运算。NumPy 的诞生弥补了这些不足。NumPy 提供了一种**存储单一数据类型
的多维数组——ndarray**。

In [10]:
# Python的列表list
l=[10,20,30,"abc",1.23,True]
l
type(l)
# 默认只输出最后一个返回值
l[2]
l[1:3]

[10, 20, 30, 'abc', 1.23, True]

list

30

[20, 30]

In [5]:
l1=[4,5,6,7]
l2=[1,2,3,4]
l1+l2
#l1*l2
#l2+1

#列表切片修改后不影响源列表
l3=l2[0:3]
l3
l3[0]=8
l3
l2

[4, 5, 6, 7, 1, 2, 3, 4]

[1, 2, 3]

[8, 2, 3]

[1, 2, 3, 4]

### 2.1.1 创建数组对象
#### 数组的属性
#### 数组的创建
- 一维数组

![](img/创建一维数组.png)  
- 二维数组  

In [2]:
#代码2-1
#导入Numpy库
import numpy as np

#创建一维数组
l1=[1,2,3,4]
n1=np.array(l1)
n1
type(n1)
n1.shape  #多少行多少列
n1.dtype  #元素的数据类型

#创建二维数组
n2=np.array([[1,2,3,4],[5,6,7,8]])
n2

# 查看数组的维度
n2.ndim
#查看数组结构（shape）
n2.shape
#查看数组类型（dtype），包含了大小，8个int型，一个int占4
n2.dtype
#查看数组元素个数（size）
n2.size
#查看数组每个元素大小（itemsize），一个int的大小
n2.itemsize

array([1, 2, 3, 4])

numpy.ndarray

(4,)

dtype('int32')

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

2

(2, 4)

dtype('int32')

8

4

In [19]:
#创建三维数组
array3=np.array([[[0.0,1,9],[2,3,0],[2,3,0]],[[3,4,5],[1,6,7],[2,3,0]]])
array3
array3.shape
array3.ndim
array3.size
array3.dtype #array仅能一种数据类型
array3.itemsize  #一个float的大小

array([[[0., 1., 9.],
        [2., 3., 0.],
        [2., 3., 0.]],

       [[3., 4., 5.],
        [1., 6., 7.],
        [2., 3., 0.]]])

(2, 3, 3)

3

18

dtype('float64')

8

In [25]:
#代码2-2
#重新设置数组的shape形状属性
a1=np.array([1,2,3,4,5,6,7,8])
a1
a1.shape

#要求变换后个数和前面一致
a1.shape=(2,4)
a1
a1.shape

a1.shape=(4,2)
a1
a1.shape

array([1, 2, 3, 4, 5, 6, 7, 8])

(8,)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

(2, 4)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

(4, 2)

In [28]:
# reshape方法
#属性不用括号，方法和函数要用括号，属性和方法都用 “对象.”的方式调用，只有函数是直接开头
a2=np.array([1,2,3,4,5,6,7,8])
a2
a2.shape

a2_new=a2.reshape(4,2)  #有返回值，不会修改原本数据，
a2_new
a2_new.shape

array([1, 2, 3, 4, 5, 6, 7, 8])

(8,)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

(4, 2)

In [1]:
# 显示所有变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [34]:
#用range创建数组，麻烦，不如arange
range(10)
type(range(10))
l1=list(range(1,101,5))
l1
a1=np.array(l1).reshape(4,5)
a1

range(0, 10)

range

[1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96]

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [36]:
#代码2-3
#使用Numpy的arange函数创建数组
np.arange(1,101,5).reshape(2,10)

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71, 76, 81, 86, 91, 96]])

In [38]:
a1=np.arange(10)  #一维的
a1
a1.shape
a1.shape=(1,10)  #二维
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

(10,)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
#代码2-4
#使用Numpy的linspace函数创建等差数列数组
a3=np.linspace(1,99)
a3

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [46]:
#代码2-5 
#使用Numpy的logspace函数创建等比数列数组
a4=np.logspace(1,256,10)
a4

array([1.00000000e+001, 2.15443469e+029, 4.64158883e+057, 1.00000000e+086,
       2.15443469e+114, 4.64158883e+142, 1.00000000e+171, 2.15443469e+199,
       4.64158883e+227, 1.00000000e+256])

In [54]:
#课堂练习 两种方法创建数组array([5,10,15,20...500]),shape不限
#方法1
a5=np.arange(5,505,5)
a5

a6=np.linspace(5,500,100)
a6

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130,
       135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195,
       200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260,
       265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320, 325,
       330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385, 390,
       395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450, 455,
       460, 465, 470, 475, 480, 485, 490, 495, 500])

array([  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
        60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100., 105., 110.,
       115., 120., 125., 130., 135., 140., 145., 150., 155., 160., 165.,
       170., 175., 180., 185., 190., 195., 200., 205., 210., 215., 220.,
       225., 230., 235., 240., 245., 250., 255., 260., 265., 270., 275.,
       280., 285., 290., 295., 300., 305., 310., 315., 320., 325., 330.,
       335., 340., 345., 350., 355., 360., 365., 370., 375., 380., 385.,
       390., 395., 400., 405., 410., 415., 420., 425., 430., 435., 440.,
       445., 450., 455., 460., 465., 470., 475., 480., 485., 490., 495.,
       500.])

- 全0和全1数组
![](img/创建全0和全1数组.png)  

In [60]:
#代码2-6
#使用Numpy的zeros函数创建全0数组
a0=np.zeros((2,3,4))  #zeros函数里的shape参数，多维的话要用元组
a0
a0.dtype

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

dtype('float64')

In [62]:
#代码2-8
#使用Numpy的ones函数创建全1数组
a11=np.ones(100,int).reshape(4,25)
a11
a11.dtype

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1]])

dtype('int32')

In [67]:
#代码2-7
#使用Numpy的eye函数创建对角单位数组
ae=np.eye(4)  #(4,4)
ae

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
#代码2-9
#使用Numpy的diag函数创建对角数组
a_diag=np.diag([8,7,6,5])
a_diag

array([[8, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 5]])

In [70]:
#代码2-10
#数组数据类型的变换
a5=np.array([1,2,3,4,5,6]).reshape(2,3)
a5
a5.dtype

a51=np.float32(a5)
a51
a51.dtype
a5  #复制出来的，a5不变

array([[1, 2, 3],
       [4, 5, 6]])

dtype('int32')

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

dtype('float32')

In [11]:
import numpy as np
a5=np.array([1,2,3,4,5,6]).reshape(2,3)
a5
a5.dtype

#a5.dtype="float32"  #直接修改
a5=a5.astype('int8')
a5.dtype
a5.itemsize

array([[1, 2, 3],
       [4, 5, 6]])

dtype('int32')

dtype('int8')

1

In [81]:
a6=np.array([1,2,3,4],dtype='int8')  #只有int可以不用引号，有int8就要引号作为字符串
a6
a6.dtype

print("\n a7")
a7=np.array([1,2,3,4],dtype=float)
a7
a7.dtype
a7.dtype=int
a7
a7.dtype

array([1, 2, 3, 4], dtype=int8)

dtype('int8')


a7


array([1., 2., 3., 4.])

dtype('float64')

array([         0, 1072693248,          0, 1073741824,          0,
       1074266112,          0, 1074790400])

dtype('int32')

### 2.1.2 生成随机数

![](img/创建随机数组.png)  

In [49]:
# 标准库random
import random
random.seed()
random.randint(1,42)
random.random()
round(random.random(),2)

37

0.3224926339307208

0.65

In [57]:
#代码2-14 
#生成随机数组（注意是Numpy库的random子库中的random函数）
import numpy as np
np.random.random(10).reshape(2,5)  #没法用round

array([[0.33812468, 0.81124237, 0.05665804, 0.33029871, 0.94590668],
       [0.3383866 , 0.88089281, 0.93961843, 0.08936833, 0.59929615]])

In [127]:
#代码2-15
#生成服从均匀分布的随机数数组（注意是Numpy库的random子库中的rand函数）
np.random.rand(3,2)
np.random.rand(2,3,3)

array([[0.78188106, 0.5924566 ],
       [0.59035143, 0.20562652],
       [0.45746225, 0.34511066]])

array([[[0.65736473, 0.74301881, 0.41893422],
        [0.26837232, 0.63142692, 0.11612449],
        [0.44417567, 0.2444061 , 0.88673777]],

       [[0.46463284, 0.17819139, 0.52818405],
        [0.82717761, 0.04628829, 0.69399866],
        [0.00670664, 0.3070071 , 0.68156093]]])

In [15]:
#生成范围在0~1、服从均匀分布的10行5列的数组。
np.random.rand(10,5)

array([[0.58438116, 0.25071855, 0.07272126, 0.90427156, 0.18641682],
       [0.13849242, 0.67992951, 0.86782711, 0.71488922, 0.88425601],
       [0.06542766, 0.46998242, 0.84393294, 0.69781891, 0.35738919],
       [0.78241104, 0.91457683, 0.28705341, 0.08068087, 0.35788144],
       [0.08355045, 0.82622798, 0.05225122, 0.70597259, 0.29737846],
       [0.08202665, 0.05007536, 0.55849174, 0.4968069 , 0.47891547],
       [0.20719313, 0.22932925, 0.29454349, 0.43823388, 0.98723836],
       [0.91268532, 0.44138373, 0.00101154, 0.67695146, 0.5718503 ],
       [0.51133162, 0.85673397, 0.02635416, 0.13599406, 0.95946271],
       [0.33114295, 0.47287357, 0.74242795, 0.53944143, 0.63266665]])

In [23]:
#生成两个2*2矩阵，并计算矩阵乘积。
n1 =np.array([[1,2],[4,5]])
n2 = np.array([[1,4],[2,5]])
n1
n2
n1*n2

array([[1, 2],
       [4, 5]])

array([[1, 4],
       [2, 5]])

array([[ 1,  8],
       [ 8, 25]])

In [119]:
#代码2-16
#生成服从正态分布的随机数数组（注意是Numpy库的random子库中的randn函数）
np.random.randn(3,2)

array([[-0.98960603, -0.89315247],
       [-1.33840727, -1.80559454],
       [ 0.25138958,  0.04991502]])

In [108]:
#代码2-17
#生成给定上下限的随机整数数组（注意是Numpy库的random子库中的randint函数）
np.random.randint(1,43,size=[2,5])

array([[ 8, 29, 16, 24, 18],
       [33, 15, 33, 18,  7]])

In [150]:
#课堂练习，创建一个数组，数值在0-1之间，间隔为0.01的数组
np.arange(0,1,0.01)
#np.linspace(0,1,101)
#课堂练习，创建一个数组，数值在0-1之间
np.round(np.array([np.random.random() for i in range(10)]),2)
np.round()

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

array([0.5 , 0.78, 0.58, 0.89, 0.89, 0.97, 0.4 , 0.16, 0.63, 0.99])

### 项目实例：全国人口数据的读取

In [12]:
# 从文本文件读取人口数据
# datas
import numpy as np
peoples = np.loadtxt("data/人口.csv",skiprows=2,delimiter=',',usecols=(range(1,13)),encoding="utf-8")
province = np.loadtxt("data/人口.csv",skiprows=2,delimiter=',',usecols=0,encoding="utf-8",dtype=str)

In [24]:
# names
province
peoples.shape
peoples[0]

array(['北京', '天津', '河北', '山西', '内蒙古 ', '辽宁', '吉林', '黑龙江 ', '上海', '江苏',
       '浙江', '安徽', '福建', '江西', '山东', '河南', '湖北', '湖南', '广东', '广西', '海南',
       '四川', '贵州', '云南', '西藏', '陕西', '甘肃', '青海', '宁夏', '新疆'], dtype='<U4')

(30, 12)

array([1035.7, 1042.9, 1048.7, 1056.9, 1068.2, 1077. , 1083.2, 1092.3,
       1097.8, 1106.2, 1113.5, 1127.9])

### 2.1.3 通过索引访问数组

In [ ]:
# 显示所有变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

- 一维数组索引  
![](img/一维数组索引.png)  

In [37]:
# 代码2-18：一维数组
#使用arange创建数组
a=np.arange(1,10)
a
#整数作为下标访问，分别访问0和5
a[[0,5]]    #只能用列表，不能元组
#范围作为下标切片
a[2:6:1]
#省略切片的开始下标，表示从0开始
a[:]
#负数作为下标
a[-10:]
#下标用来修改数组元素的值
a[0:7:2]=[9,8,7,6]
a
#步长为负数时，切片的开始下标必须大于结束下标（也可以不，只是没数据，不报错）
a[-1::-2]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 6])

array([3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([9, 2, 8, 4, 7, 6, 6, 8, 9])

array([9, 6, 7, 8, 9])

- 二维数组索引
![](img/二维数组索引.png)  

In [4]:
#代码2-19：多维数组
#创建二维数组
a2=np.arange(1,21).reshape(4,5)
a2
#二维数组只有一个下标索引代表行
a2[1]
#索引访问第0行的第3和第4列
a2[0,3:]
#索引第2和第3行的3-4列
a2[2:,3:]
#索引第2列
a2[:,2:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

array([ 6,  7,  8,  9, 10])

array([4, 5])

array([[14, 15],
       [19, 20]])

array([[ 3],
       [ 8],
       [13],
       [18]])

In [5]:
#代码2-20
#从两个序列对应位置取出整数组成下标索引
a2[0:3,1:4]
a2[[0,1,2],[1,2,0]]  #或者a2[(0,1,2),(1,2,0)]，错误的：a2[[0,1,2],[1,2]]
#索引第2，3行中的第0，2，3列（不连续的列使用元组表示）
a2[0:3,(1,2)]
#利用布尔数组来索引
a2
a2[[True,False,True,False],2:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

array([ 2,  8, 11])

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

array([[ 3,  4],
       [13, 14]])

In [6]:
a2>5  #广播机制
index=a2 % 2==0
index

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [7]:
a2[index]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### 项目实例：全国人口数据的索引和切片

In [9]:
# 从文本文件读取人口数据
peoples = np.loadtxt("data/人口.csv",skiprows=2,delimiter=',',usecols=(range(1,13)),encoding="utf-8")
province = np.loadtxt("data/人口.csv",skiprows=2,delimiter=',',usecols=0,encoding="utf-8",dtype=str)
province

array(['北京', '天津', '河北', '山西', '内蒙古 ', '辽宁', '吉林', '黑龙江 ', '上海', '江苏',
       '浙江', '安徽', '福建', '江西', '山东', '河南', '湖北', '湖南', '广东', '广西', '海南',
       '四川', '贵州', '云南', '西藏', '陕西', '甘肃', '青海', '宁夏', '新疆'], dtype='<U4')

In [85]:
# 读取北京的数据
peoples[0]
# 读取上海的人口数据
flag=province=="上海"
peoples[flag]
#peoples[True]  #等价于peoples


# 读取上海1994年的人口数据
peoples[province=="上海",4]


# 读取北京、上海、广东所有年份的人口数据
f1=province=="上海"
f2=province=="北京"
f3=province=="广东"
f4=f1+f2+f3
f4
print("here")
peoples[f4]


# 读取北京、上海、广东1993到2000年的数据
peoples[f4,3:11]


# 读取北京1991年、上海1994年，广东1995年的数据
peoples[(0,8,18),(1,4,5)]


#读取北京、上海，广东1991年、1994年、1995年的数据
peoples[[[0],[8],[18]],(1,4,5)]
peoples[[0,8,18],[[1,4,5],[1,4,5],[1,4,5]]]
peoples[np.ix_([0,8,18],[1,4,5])]

array([1035.7, 1042.9, 1048.7, 1056.9, 1068.2, 1077. , 1083.2, 1092.3,
       1097.8, 1106.2, 1113.5, 1127.9])

array([[1283.4, 1287.2, 1289.4, 1294.7, 1298.8, 1301.4, 1304.4, 1305.5,
        1306.6, 1313.1, 1321.6, 1327.1]])

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

array([1298.8])

array([ True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False])

here


array([[1035.7, 1042.9, 1048.7, 1056.9, 1068.2, 1077. , 1083.2, 1092.3,
        1097.8, 1106.2, 1113.5, 1127.9],
       [1283.4, 1287.2, 1289.4, 1294.7, 1298.8, 1301.4, 1304.4, 1305.5,
        1306.6, 1313.1, 1321.6, 1327.1],
       [6246.3, 6349. , 6463.2, 6581.6, 6691.5, 6788.7, 6896.8, 7013.7,
        7115.6, 7298.9, 7498.5, 7565.3]])

array([[1056.9, 1068.2, 1077. , 1083.2, 1092.3, 1097.8, 1106.2, 1113.5],
       [1294.7, 1298.8, 1301.4, 1304.4, 1305.5, 1306.6, 1313.1, 1321.6],
       [6581.6, 6691.5, 6788.7, 6896.8, 7013.7, 7115.6, 7298.9, 7498.5]])

array([1042.9, 1298.8, 6788.7])

array([[1042.9, 1068.2, 1077. ],
       [1287.2, 1298.8, 1301.4],
       [6349. , 6691.5, 6788.7]])

array([[1042.9, 1298.8, 6788.7],
       [1042.9, 1298.8, 6788.7],
       [1042.9, 1298.8, 6788.7]])

array([[1042.9, 1068.2, 1077. ],
       [1287.2, 1298.8, 1301.4],
       [6349. , 6691.5, 6788.7]])

In [64]:
# 前5行的省市名称
province[:5]
# 1992年各省市人口数据
peoples[:,2]
# 山西历年人口数据
peoples[province=="山西"]

# 河北，山西，内蒙1994年到1999年的数据

# 北京、上海、广东1991年、1994年和1995年的数据


array(['北京', '天津', '河北', '山西', '内蒙古 '], dtype='<U4')

array([ 1048.7,   882.7,  6249.3,  2919.1,  2178.5,  3957.9,  2474. ,
        3526.2,  1289.4,  6767.5,  4285.9,  5817.5,  3066.9,  3827. ,
        8579.8,  8811.5,  5513.6,  6209.2,  6463.2,  4359.4,   671.3,
       10942.9,  3301. ,  3767.1,   225.3,  3340.3,  2288.1,   443.1,
         482.3,  1554.1])

array([[2845.2, 2883.4, 2919.1, 2955.5, 2990.9, 3025.7, 3059.2, 3091.3,
        3113.3, 3145.1, 3196.2, 3220.3]])

### 2.1.4 变换数组的形态

![](img/数组变形.png)  

In [5]:
#代码2-21
#arange创建一维数组
a1=np.arange(1,13)
a1
#设置数组的形状
a1=a1.reshape(3,-1)   #-1表示所有，反正规定了一个另一个也就确认了
#查看数组的维度
a1.shape
a1.ndim

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

(3, 4)

2

In [90]:
#代码2-22
#创建二维数组（使用arange和reshape）
a1
#使用ravel方法按行展平数组
a1.ravel()
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
#代码2-23
#使用flatten函数按行展平数组（横向）
a1.flatten()
#使用flatten函数按列展平数组（纵向）
a1.flatten("F")

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

![11](img/hstack和vstack.jpg)  

In [18]:
#代码2-24
#创建一个3X4的二维数组
a2=np.arange(0,12).reshape(3,4)
a2
#上一个数组*3创建另一个数组
a3=a2*3
a3
#使用hstack函数将两个数组横向组合
np.hstack((a2,a3))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

array([[ 0,  1,  2,  3,  0,  3,  6,  9],
       [ 4,  5,  6,  7, 12, 15, 18, 21],
       [ 8,  9, 10, 11, 24, 27, 30, 33]])

In [19]:
#代码2-25
#使用vstack函数将两个数组纵向组合，vertical
np.vstack((a2,a3))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [20]:
#代码2-26
#使用concatenate函数组合数组，横向：axis=1；纵向：axis=0，axis默认是0
np.concatenate((a2,a3))  #因为默认axis=0
np.concatenate((a2,a3),axis=1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

array([[ 0,  1,  2,  3,  0,  3,  6,  9],
       [ 4,  5,  6,  7, 12, 15, 18, 21],
       [ 8,  9, 10, 11, 24, 27, 30, 33]])

![](img/hsplit和vsplit.jpg)  

In [8]:
#代码2-27
#使用hsplit函数实现数组的横向分割
a4=np.hstack((a1,a2))
np.hsplit(a4,4)   #用的数字就表示分成几份
# np.hsplit(np.hstack((a1,a2)),[1,2])   #用序列[a,b]表示分三部分，a行（列），(b-a)行（列）剩下的(n-a-b)组成行（列）
np.hsplit(a4,[2,7,5,4])  #前面7列切了后面4列也能切

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]]),
 array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4,  0,  1,  2],
        [ 7,  8,  4,  5,  6],
        [11, 12,  8,  9, 10]]),
 array([], shape=(3, 0), dtype=int32),
 array([], shape=(3, 0), dtype=int32),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

In [10]:
#代码2-28
#使用vsplit函数实现数组的纵向分割
a3=np.hstack((a1,a2))  #先合并
a3
np.vsplit(a3,[1,3])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 1,  2,  3,  4,  0,  1,  2,  3],
       [ 5,  6,  7,  8,  4,  5,  6,  7],
       [ 9, 10, 11, 12,  8,  9, 10, 11]])

[array([[1, 2, 3, 4, 0, 1, 2, 3]]),
 array([[ 5,  6,  7,  8,  4,  5,  6,  7],
        [ 9, 10, 11, 12,  8,  9, 10, 11]]),
 array([], shape=(0, 8), dtype=int32)]

In [28]:
#代码2-29
#使用split函数加上axis参数实现数组的横向和纵向分割，1是纵向，0是横向，默认0
a=np.arange(1,49).reshape(6,8)
a
np.split(a,2)
np.split(a,2,axis=1)
np.split(a,(4,))
np.splite(a,(2,2,2,2))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]])]

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28],
        [33, 34, 35, 36],
        [41, 42, 43, 44]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32],
        [37, 38, 39, 40],
        [45, 46, 47, 48]])]

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]])]

AttributeError: module 'numpy' has no attribute 'splite'

In [38]:
#创建一个（16，9）的数组，进行横向、纵向拆分，分别得到（3，9）（10，9）（5，9）的子数组
b=np.arange(0,144).reshape(16,9)
b
np.vsplit(b,[3,8,0,10])

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59,  60,  61,  62],
       [ 63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116],
       [117, 118, 119, 120, 121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141, 142, 143]])

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([[27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59, 60, 61, 62],
        [63, 64, 65, 66, 67, 68, 69, 70, 71]]),
 array([], shape=(0, 9), dtype=int32),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59, 60, 61, 62],
        [63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80],
        [81, 82, 83, 84, 85, 86, 87, 88, 89]]),
 array([[ 90,  91,  92,  93,  94,  95,  96,  97,  98],
        [ 99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109

In [ ]:
# 关于reshape
#-1

![](img/tile和repeat.jpg)  

In [45]:
# tile函数和repeat方法；函数的操作一般是有返回值的，方法的操作一般是原地修改
a=np.arange(6).reshape(2,3)
a
np.tile(a,(2,3))  #2行3列
a.repeat(3,axis=1)
a.repeat(3,axis=0)

array([[0, 1, 2],
       [3, 4, 5]])

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

array([[0, 0, 0, 1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4, 5, 5, 5]])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

### 课堂练习

In [59]:
#课堂练习1：创建一个数值从0到1，间隔为0.01的数组

#课堂练习2：创建100个服从正态分布的随机数

#课堂练习3：对创建的数组进行数组运算

#课堂练习4：创建一个国际象棋的棋盘：黑为1，白为0
a=np.array([1,0,0,1]).reshape(2,2)
a
np.tile(a,(4,4))

b=np.zeros((8,8),dtype=int)
b[::2,::2]=1
b[1::2,1::2]=1
b

array([[1, 0],
       [0, 1]])

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### 项目实例：全国人口数据人口的切片（续）

In [62]:
# 从文本文件读取人口数据
peoples = np.loadtxt("data/人口.csv",skiprows=2,delimiter=',',usecols=(range(1,13)),encoding="utf-8")
province = np.loadtxt("data/人口.csv",skiprows=2,delimiter=',',usecols=0,encoding="utf-8",dtype=str)
# 从文本文件读取人口数据
province
peoples

array(['北京', '天津', '河北', '山西', '内蒙古 ', '辽宁', '吉林', '黑龙江 ', '上海', '江苏',
       '浙江', '安徽', '福建', '江西', '山东', '河南', '湖北', '湖南', '广东', '广西', '海南',
       '四川', '贵州', '云南', '西藏', '陕西', '甘肃', '青海', '宁夏', '新疆'], dtype='<U4')

array([[ 1035.7,  1042.9,  1048.7,  1056.9,  1068.2,  1077. ,  1083.2,
         1092.3,  1097.8,  1106.2,  1113.5,  1127.9],
       [  870.5,   876.6,   882.7,   889.6,   894.5,   898.6,   902.4,
          905.1,   910.7,   916.2,   918.7,   923.7],
       [ 6116.8,  6183.2,  6249.3,  6309.6,  6366. ,  6420.5,  6461. ,
         6508.1,  6555.3,  6602.2,  6670.9,  6702.5],
       [ 2845.2,  2883.4,  2919.1,  2955.5,  2990.9,  3025.7,  3059.2,
         3091.3,  3113.3,  3145.1,  3196.2,  3220.3],
       [ 2149.4,  2164.8,  2178.5,  2198. ,  2217.4,  2237.2,  2263. ,
         2288.5,  2310.2,  2329.5,  2300.9,  2319.2],
       [ 3917.4,  3938.5,  3957.9,  3982.9,  4007.2,  4034. ,  4056.8,
         4077.1,  4090.4,  4103.2,  4135.3,  4147. ],
       [ 2440.2,  2459.7,  2474. ,  2496.1,  2515.6,  2550.9,  2579.1,
         2600.1,  2603.2,  2616.1,  2627.3,  2637.1],
       [ 3488.9,  3510.7,  3526.2,  3538.9,  3557.6,  3576.8,  3605.1,
         3628.5,  3642. ,  3660.8,  3698.1,  3715.4],


In [81]:
# 前五行是哪些省市
province[:5]

# 1991年各省市人口(某一列)

# 山西省历年人口数据（某一行）
peoples[province=="山西"]

# 河北山西内蒙古历年人口数据
peoples[np.any([province=="河北",province=="山西",province=="内蒙古"],axis=0)]

array(['北京', '天津', '河北', '山西', '内蒙古 '], dtype='<U4')

array([[2845.2, 2883.4, 2919.1, 2955.5, 2990.9, 3025.7, 3059.2, 3091.3,
        3113.3, 3145.1, 3196.2, 3220.3]])

array([[6116.8, 6183.2, 6249.3, 6309.6, 6366. , 6420.5, 6461. , 6508.1,
        6555.3, 6602.2, 6670.9, 6702.5],
       [2845.2, 2883.4, 2919.1, 2955.5, 2990.9, 3025.7, 3059.2, 3091.3,
        3113.3, 3145.1, 3196.2, 3220.3]])

![](img/数组布尔索引.png)  

In [77]:
# 预备知识：条件索引和切片
a2=np.arange(1,13)
a2
# 截取奇数
a2[a2%2==1]

# 能被2和3同时整除的数
a2[(a2%2==0) & (a2%3==0)]
a2[np.all([a2%2==0,a2%3==0],axis=0)]

# 能被2或3整除的数
a2[(a2%2==0) | (a2%3==0)]
a2[np.any([a2%2==0,a2%3==0],axis=0)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([ 1,  3,  5,  7,  9, 11])

array([ 6, 12])

array([ 6, 12])

array([ 2,  3,  4,  6,  8,  9, 10, 12])

array([ 2,  3,  4,  6,  8,  9, 10, 12])

In [11]:
# 从文本文件读取人口数据
peoples = np.loadtxt("data/人口.csv",skiprows=2,delimiter=',',usecols=(range(1,13)),encoding="utf-8")
province = np.loadtxt("data/人口.csv",skiprows=2,delimiter=',',usecols=0,encoding="utf-8",dtype=str)

# 广东省历年人口数据（不知道广东省在peoples的行号）
peoples[province=="广东"]
# 广东省1991、1994、1997年的人口数据
peoples[province=="广东",[1,4,7]]
# 北京上海广东1991,1994,1997年的人口数据
peoples[np.any([province=="北京",province=="上海",province=="广东"],axis=0),1:8:3]
#等价于 peoples[np.any([province=="北京",province=="上海",province=="广东"],axis=0)][:,(1,4,7)]

array([[6246.3, 6349. , 6463.2, 6581.6, 6691.5, 6788.7, 6896.8, 7013.7,
        7115.6, 7298.9, 7498.5, 7565.3]])

array([6349. , 6691.5, 7013.7])

array([[1042.9, 1068.2, 1092.3],
       [1287.2, 1298.8, 1305.5],
       [6349. , 6691.5, 7013.7]])

In [41]:
# 另一种方式
# 找到省市的序号
np.where(province=="北京")  #单个可以不用[0]；多个就要
np.where(province=="北京")[0]
peoples[0]
peoples[[np.where(province=="北京")[0],np.where(province=="天津")[0]]]

(array([0], dtype=int64),)

numpy.ndarray

array([1035.7, 1042.9, 1048.7, 1056.9, 1068.2, 1077. , 1083.2, 1092.3,
       1097.8, 1106.2, 1113.5, 1127.9])

array([1042.9])

In [7]:
np.where((province=="北京") | (province=="天津"))

(array([0, 1], dtype=int64),)

## 2.2 掌握NumPy矩阵与通用函数
NumPy 对于多维数组的运算，默认情况下并不使用矩阵运算。如果需要对数组进行矩
阵运算，则可以调用相应的函数。

In [2]:
# 显示所有变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np

### 2.2.1 创建Numpy矩阵

In [10]:
# 新版numpy不再更新矩阵的支持，由二维数组取代
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[1,3],[5,7],[9,11]])
a1;a2
# a1*a2  目前是数组，没法直接用矩阵的乘法运算
np.dot(a1,a2)

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

array([[ 38,  50],
       [ 83, 113]])

In [48]:
#matrix函数将数组转成矩阵matrix类型
m1=np.matrix(a1)
m1
m2=np.matrix(a2);m2
m1*m2
m1.A  #矩阵转成数组array
m1.T
m1.H
m1.I

matrix([[1, 2, 3],
        [4, 5, 6]])

matrix([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])

matrix([[ 38,  50],
        [ 83, 113]])

array([[1, 2, 3],
       [4, 5, 6]])

matrix([[1, 4],
        [2, 5],
        [3, 6]])

matrix([[1, 4],
        [2, 5],
        [3, 6]])

matrix([[-0.94444444,  0.44444444],
        [-0.11111111,  0.11111111],
        [ 0.72222222, -0.22222222]])

### 2.2.2 掌握ufunc函数

![](img/二维数组计算.png)  

In [18]:
#代码2-34：数组的四则运算
#创建两个一维数组x和y
x=np.array([1,2,3])
y=np.array([4,5,6])
x;y
#数组相加
x+y
np.add(x,y)  #通用函数
#数组相减
x-y
np.subtract(x,y)
#数组相乘
x*y
np.multiply(x,y)
#数组相除
x/y
np.divide(x,y)
#数组幂运算
x**y
np.power(x,y)

array([1, 2, 3])

array([4, 5, 6])

array([5, 7, 9])

array([5, 7, 9])

array([-3, -3, -3])

array([-3, -3, -3])

array([ 4, 10, 18])

array([ 4, 10, 18])

array([0.25, 0.4 , 0.5 ])

array([0.25, 0.4 , 0.5 ])

array([  1,  32, 729])

array([  1,  32, 729])

In [21]:
#代码2-35：数组的比较运算
#>,<,==,>=,<=,!=
x=np.array([4,2,3])
y=np.array([1,2,6])
x;y

x<y

x>y

x==y
np.equal(x,y)

x>=y

x!=y
np.not_equal(x,y)

x[x>y]

array([4, 2, 3])

array([1, 2, 6])

array([False, False,  True])

array([ True, False, False])

array([False,  True, False])

array([False,  True, False])

array([ True,  True, False])

array([ True, False,  True])

array([ True, False,  True])

array([4])

In [29]:
#代码2-36：数组的逻辑运算
#all
np.all(x>y)
np.all(x!=y)
#any
np.any(x>y)
np.any(x==y)
x=x.reshape(1,3)  #调用方法是不会原地修改的，要重新赋值
y=y.reshape(1,3)
np.any(x==y,axis=0)

False

False

True

True

array([False,  True, False])

In [44]:
#代码2-37
#二维数组的广播机制（4，8）和（2，2）（4，）（4，1）（4，2）（1，8）（1，4）
a=np.arange(32).reshape(4,8);a
# b=np.arange(4).reshape(2,2);b      #(2,2)不行
# b=np.arange(4).reshape(4,);b       #(4,)不行
b=np.arange(4).reshape(4,1);b        #（4，1）可以
a+b
# c=np.arange(8).reshape(4,2);c      #(4,2)不行
c=np.arange(8).reshape(1,8);c        #（1，8）可以
a+c
# d=d=np.arange(4).reshape(1,4);d    #（1，4）不行

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

array([[0],
       [1],
       [2],
       [3]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [27, 28, 29, 30, 31, 32, 33, 34]])

array([[0, 1, 2, 3, 4, 5, 6, 7]])

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 8, 10, 12, 14, 16, 18, 20, 22],
       [16, 18, 20, 22, 24, 26, 28, 30],
       [24, 26, 28, 30, 32, 34, 36, 38]])

![](img/数组的广播.png)  

In [59]:
#函数有没有返回值？是不是本地修改？  --- sort()没有返回值，函数和方法都有返回值
a=np.arange(3)
print(a)
b=a.astype(float)
print(b)

[0 1 2]
[0. 1. 2.]


## 2.3 利用NumPy进行统计分析
在NumPy 中，数组运算更为简捷而快速，通常比等价的Python 方式快几倍，特别是
处理数组统计计算与分析的情况时。

### 2.3.1 读写文件

In [53]:
#代码2-39：二进制存储数据
#导入Numpy库
import numpy as np
#创建一个数组
a=np.arange(100).reshape(10,-1);a
#使用save保存数组到文件
np.save("./data/save_a1",a)
#打印数组


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [61]:
#代码2-40：多个数组的存储
#创建两个数组
a=np.arange(9).reshape(3,3)
a1=np.arange(0,1,0.01)
a;a1
#使用savez保存多个数组到文件
np.savez("./data/save_arrs",x=a,y=a1)  #x,y随便的，相当于命名
#打印数组


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [76]:
#代码2-41：二进制读取文件
#读取单个数组的文件
load_a1=np.load("./data/save_a1.npy")
load_a1
#读取多个数组的文件
load_arrs=np.load("./data/save_arrs.npz")
load_arrs.files
x1=load_arrs['x']
y1=load_arrs[load_arrs.files[1]]
x1;y1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

['x', 'y']

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

### 项目实例：全国人口数据的二进制存储和读取

In [2]:
# 从文本文件读取人口数据
peoples=np.loadtxt("./data/人口.csv",skiprows=2,delimiter=",",usecols=(range(1,13)),encoding="utf-8")
province=np.loadtxt("./data/人口.csv",skiprows=2,delimiter=",",usecols=(0),encoding="utf-8",dtype=str)
np.savez("./data/renkou.npz",p=peoples,pro=province)

In [3]:
# 读取人口数据二进制文件
renkou=np.load("./data/renkou.npz")
renkou.files
peoples_=renkou['p']
province_=renkou['pro']
peoples_;province_

['p', 'pro']

array([[ 1035.7,  1042.9,  1048.7,  1056.9,  1068.2,  1077. ,  1083.2,
         1092.3,  1097.8,  1106.2,  1113.5,  1127.9],
       [  870.5,   876.6,   882.7,   889.6,   894.5,   898.6,   902.4,
          905.1,   910.7,   916.2,   918.7,   923.7],
       [ 6116.8,  6183.2,  6249.3,  6309.6,  6366. ,  6420.5,  6461. ,
         6508.1,  6555.3,  6602.2,  6670.9,  6702.5],
       [ 2845.2,  2883.4,  2919.1,  2955.5,  2990.9,  3025.7,  3059.2,
         3091.3,  3113.3,  3145.1,  3196.2,  3220.3],
       [ 2149.4,  2164.8,  2178.5,  2198. ,  2217.4,  2237.2,  2263. ,
         2288.5,  2310.2,  2329.5,  2300.9,  2319.2],
       [ 3917.4,  3938.5,  3957.9,  3982.9,  4007.2,  4034. ,  4056.8,
         4077.1,  4090.4,  4103.2,  4135.3,  4147. ],
       [ 2440.2,  2459.7,  2474. ,  2496.1,  2515.6,  2550.9,  2579.1,
         2600.1,  2603.2,  2616.1,  2627.3,  2637.1],
       [ 3488.9,  3510.7,  3526.2,  3538.9,  3557.6,  3576.8,  3605.1,
         3628.5,  3642. ,  3660.8,  3698.1,  3715.4],


array(['北京', '天津', '河北', '山西', '内蒙古 ', '辽宁', '吉林', '黑龙江 ', '上海', '江苏',
       '浙江', '安徽', '福建', '江西', '山东', '河南', '湖北', '湖南', '广东', '广西', '海南',
       '四川', '贵州', '云南', '西藏', '陕西', '甘肃', '青海', '宁夏', '新疆'], dtype='<U4')

In [98]:
#代码2-42：文本文件的存储与读取
#创建数组
a=np.arange(0,20,0.5).reshape(5,8)
a
#存储文本文件savetxt
np.savetxt("./data/save_txt",a,delimiter=",")
#读取文本文件loadtxt
b=np.loadtxt("./data/save_txt",delimiter=",")
b

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5],
       [ 4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5],
       [12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5],
       [16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5]])

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5],
       [ 4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5],
       [12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5],
       [16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5]])

In [100]:
#代码2-43：使用genfromtxt函数读取数据
np.genfromtxt("./data/save_txt",delimiter=",",skip_header=1)  #跳过一行

array([[ 4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5],
       [12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5],
       [16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5]])

In [ ]:
np.genfromtxt?  #执行可以直接看手册

In [103]:
# genfromtxt 读取人口数据
np.genfromtxt("./data/人口.csv",delimiter=",",skip_header=2,usecols=(0),dtype=str,encoding="utf-8")

array(['北京', '天津', '河北', '山西', '内蒙古 ', '辽宁', '吉林', '黑龙江 ', '上海', '江苏',
       '浙江', '安徽', '福建', '江西', '山东', '河南', '湖北', '湖南', '广东', '广西', '海南',
       '四川', '贵州', '云南', '西藏', '陕西', '甘肃', '青海', '宁夏', '新疆'], dtype='<U4')

### 课堂练习

In [ ]:
#课堂练习：生成2个2行2列的矩阵，计算矩阵乘积


In [2]:
# 生成正反对角线都为1，其余为0的矩阵


### 2.3.2 使用数组进行简单的统计分析
- 排序
- 去重
- 统计函数

![](img/数组排序-1.jpg)  

In [46]:
#代码2-44：sort排序
#设置随机数种子
np.random.seed(33)
#创建一维随机数组
a1=np.random.randint(1,10,size=10)
a1
#数组排序
a1.sort()  #等价于a1=np.sort(a1)
a1

array([5, 8, 9, 3, 3, 4, 7, 4, 4, 2])

array([2, 3, 3, 4, 4, 4, 5, 7, 8, 9])

In [83]:
#生成二维随机数组
np.random.seed(11)
a2=np.random.randint(1,10,9).reshape(3,3)  #size=9
a2
#沿横轴排序
a2.sort()   #默认按1排序，即行
a2
#沿纵轴排序
a2.sort(axis=0)
a2

array([[1, 2, 8],
       [2, 8, 3],
       [9, 1, 1]])

array([[1, 2, 8],
       [2, 3, 8],
       [1, 1, 9]])

array([[1, 1, 8],
       [1, 2, 8],
       [2, 3, 9]])

In [96]:
#代码2-46和2-47
#argsort：排序后的原始下标
a3=np.array([2,3,1,5]).reshape(2,2)
a3
a3.argsort()  #默认最大的轴，即1轴
a3.argsort(axis=0)


#lexsort：间接排序
name=np.array(['jb','lis','wa','liu','wa'])
age=np.array([41,24,53,74,51])
name;age
i1=np.lexsort((name,age))  #两个数组是对应的，因此一个排序另一个也要排序，默认先按后面的排，即按照age排
i2=np.lexsort((age,name))  #先按name排，相等再按age排
i1;i2

#lexsort应用
[(name[i],age[i])for i in i1]   #列表解析式，可以重复
dict(zip(name[i1],age[i1]))  #字典，但不能重复
np.vstack((name[i1],age[i1]))
#name排
[(name[i],age[i])for i in i2]   #列表解析式，可以重复
dict(zip(name[i2],age[i2]))  #字典，但不能重复

array([[2, 3],
       [1, 5]])

array([[0, 1],
       [0, 1]], dtype=int64)

array([[1, 0],
       [0, 1]], dtype=int64)

array(['jb', 'lis', 'wa', 'liu', 'wa'], dtype='<U3')

array([41, 24, 53, 74, 51])

array([1, 0, 4, 2, 3], dtype=int64)

array([0, 1, 3, 4, 2], dtype=int64)

[('lis', 24), ('jb', 41), ('wa', 51), ('wa', 53), ('liu', 74)]

{'lis': 24, 'jb': 41, 'wa': 53, 'liu': 74}

array([['lis', 'jb', 'wa', 'wa', 'liu'],
       ['24', '41', '51', '53', '74']], dtype='<U11')

[('jb', 41), ('lis', 24), ('liu', 74), ('wa', 51), ('wa', 53)]

{'jb': 41, 'lis': 24, 'liu': 74, 'wa': 53}

In [110]:
#代码2-47：数组内去重
#创建字符串数组
name=np.array(['jb','lis','wa','liu','wa'])
np.unique(name)
#数组去重
name
set(name)
#不用Numpy的实现

#创建整型数组
a4=np.random.randint(1,5,size=10)
a4
#整型数组去重
np.unique(a4)

array(['jb', 'lis', 'liu', 'wa'], dtype='<U3')

array(['jb', 'lis', 'wa', 'liu', 'wa'], dtype='<U3')

{'jb', 'lis', 'liu', 'wa'}

array([4, 1, 2, 4, 1, 1, 2, 4, 3, 4])

array([1, 2, 3, 4])

In [ ]:
#代码2-48和代码2-49：重复数据
#tile函数实现数据重复

#repeat函数实现数据重复


![](img/数组最大最小值.png)  

In [119]:
#代码2-50：Numpy中常用统计函数
#创建二维数组
a=np.arange(30).reshape(5,6)
a
#数组的和
a.sum()
#沿横轴的和(行的和)
a.sum(axis=1)
#沿纵轴的和（列的和）
a.sum(axis=0)
#数组均值
a.mean()
#沿横轴均值
a.mean(axis=1)
#沿纵轴均值
a.mean(axis=0)
#标准差和方差
a.std()
#最大值和最小值
a.max();a.min()
#最大值和最小值的索引（重点）
a.argmax();a.argmin()

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

435

array([ 15,  51,  87, 123, 159])

array([60, 65, 70, 75, 80, 85])

14.5

array([ 2.5,  8.5, 14.5, 20.5, 26.5])

array([12., 13., 14., 15., 16., 17.])

8.65544144839919

29

0

29

0

In [120]:
#代码2-51：cumsum和cumprod
#创建数组

#累计和
a
np.cumsum(a,axis=0)
#累计积


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14, 16],
       [18, 21, 24, 27, 30, 33],
       [36, 40, 44, 48, 52, 56],
       [60, 65, 70, 75, 80, 85]])

### 2.3.3 任务实现

In [ ]:
# 显示所有变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [130]:
#代码2-52：花萼长度数据的统计分析

#读取文件中的数据
iris=np.loadtxt("data/iris_sepal_length.csv")
#打印花萼长度数组
# iris
#排序
iris.sort()
iris
#去重
np.unique(iris)  #这些都不会修改原本值
#求和
iris.sum()
#累计和
iris.cumsum()
#累计积
iris.cumprod()
#均值
iris.mean()
#标准差
iris.std()
#方差
iris.var()
#最小值
iris.min()
#最大值
iris.max()

array([4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1,
       5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4,
       5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.9, 5.9, 5.9, 6. , 6. , 6. , 6. , 6. , 6. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3,
       6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5,
       6.5, 6.5, 6.5, 6.6, 6.6, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7,
       6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7. , 7.1, 7.2, 7.2, 7.2, 7.3,
       7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

array([4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9])

876.5

array([  4.3,   8.7,  13.1,  17.5,  22. ,  26.6,  31.2,  35.8,  40.4,
        45.1,  49.8,  54.6,  59.4,  64.2,  69. ,  73.8,  78.7,  83.6,
        88.5,  93.4,  98.3, 103.2, 108.2, 113.2, 118.2, 123.2, 128.2,
       133.2, 138.2, 143.2, 148.2, 153.2, 158.3, 163.4, 168.5, 173.6,
       178.7, 183.8, 188.9, 194. , 199.1, 204.3, 209.5, 214.7, 219.9,
       225.2, 230.6, 236. , 241.4, 246.8, 252.2, 257.6, 263.1, 268.6,
       274.1, 279.6, 285.1, 290.6, 296.1, 301.7, 307.3, 312.9, 318.5,
       324.1, 329.7, 335.4, 341.1, 346.8, 352.5, 358.2, 363.9, 369.6,
       375.3, 381.1, 386.9, 392.7, 398.5, 404.3, 410.1, 415.9, 421.8,
       427.7, 433.6, 439.6, 445.6, 451.6, 457.6, 463.6, 469.6, 475.7,
       481.8, 487.9, 494. , 500.1, 506.2, 512.4, 518.6, 524.8, 531. ,
       537.3, 543.6, 549.9, 556.2, 562.5, 568.8, 575.1, 581.4, 587.7,
       594.1, 600.5, 606.9, 613.3, 619.7, 626.1, 632.5, 639. , 645.5,
       652. , 658.5, 665. , 671.6, 678.2, 684.9, 691.6, 698.3, 705. ,
       711.7, 718.4,

array([4.30000000e+000, 1.89200000e+001, 8.32480000e+001, 3.66291200e+002,
       1.64831040e+003, 7.58222784e+003, 3.48782481e+004, 1.60439941e+005,
       7.38023729e+005, 3.46871153e+006, 1.63029442e+007, 7.82541320e+007,
       3.75619834e+008, 1.80297520e+009, 8.65428097e+009, 4.15405487e+010,
       2.03548688e+011, 9.97388573e+011, 4.88720401e+012, 2.39472996e+013,
       1.17341768e+014, 5.74974664e+014, 2.87487332e+015, 1.43743666e+016,
       7.18718331e+016, 3.59359165e+017, 1.79679583e+018, 8.98397913e+018,
       4.49198957e+019, 2.24599478e+020, 1.12299739e+021, 5.61498696e+021,
       2.86364335e+022, 1.46045811e+023, 7.44833635e+023, 3.79865154e+024,
       1.93731228e+025, 9.88029265e+025, 5.03894925e+026, 2.56986412e+027,
       1.31063070e+028, 6.81527964e+028, 3.54394541e+029, 1.84285162e+030,
       9.58282840e+030, 5.07889905e+031, 2.74260549e+032, 1.48100696e+033,
       7.99743760e+033, 4.31861631e+034, 2.33205280e+035, 1.25930851e+036,
       6.92619683e+036, 3

5.843333333333334

0.8253012917851409

0.6811222222222223

4.3

7.9

In [4]:
# 国际象棋棋盘数组


### 项目实例：全国人口数据的统计计算

In [5]:
# 从文本文件读取人口数据
peoples = np.loadtxt("data/人口.csv",skiprows=2,delimiter=',',usecols=(range(1,13)),encoding="utf-8")
province = np.loadtxt("data/人口.csv",skiprows=2,delimiter=',',usecols=0,encoding="utf-8",dtype=str)

In [6]:
# 1990年全国人口总和
peoples[:,0].sum()
# 2001年全国人口总和
p01=peoples[:,11]
p01.sum()
# 2001年各省市人口的均值和标准差
p01.mean()
p01.std()
# 广东1990年的人口
peoples[province=="广东",0]
# 广东每年人口增长值
np.diff(peoples[province=="广东"])
# 东北三省1990年人口之和
three=peoples[np.any([province=="辽宁",province=="吉林",province=="黑龙江 "],axis=0)]
np.sum(three[:,0])
# 东北三省2001年人口之和
np.sum(three[:,11])
# 东北三省每年人口增长值
np.diff(peoples[np.any([province=="辽宁",province=="吉林",province=="黑龙江 "],axis=0)])
# 各个省历年人口之和
np.sum(peoples,axis=0)
# 1990年人口最多的省份
province[np.argmax(peoples[:,0])]
# 2001年人口最多的省份
province[np.argmax(peoples[:,11])]
# 2001年人口最少的省份
province[np.argmin(peoples[:,11])]

112955.3

121332.49999999999

4044.416666666666

2638.70154824721

array([6246.3])

array([[102.7, 114.2, 118.4, 109.9,  97.2, 108.1, 116.9, 101.9, 183.3,
        199.6,  66.8]])

9846.5

10499.5

array([[21.1, 19.4, 25. , 24.3, 26.8, 22.8, 20.3, 13.3, 12.8, 32.1, 11.7],
       [19.5, 14.3, 22.1, 19.5, 35.3, 28.2, 21. ,  3.1, 12.9, 11.2,  9.8],
       [21.8, 15.5, 12.7, 18.7, 19.2, 28.3, 23.4, 13.5, 18.8, 37.3, 17.3]])

array([112955.3, 114190.8, 115242.8, 116296.6, 117353.7, 118467.6,
       119546.1, 117539.5, 118438.3, 119419.1, 120581. , 121332.5])

'四川'

'河南'

'西藏'